// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/charts": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/showcase": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/charts" | "/dashboard" | "/showcase";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/charts.tsx": {
    id: "routes/charts";
    page: "/charts";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/showcase.tsx": {
    id: "routes/showcase";
    page: "/showcase";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/_index": typeof import("./src/routes/_index.tsx");
  "routes/charts": typeof import("./src/routes/charts.tsx");
  "routes/dashboard": typeof import("./src/routes/dashboard.tsx");
  "routes/showcase": typeof import("./src/routes/showcase.tsx");
};